class Deck {
        headerMessages(){
        const deck = [
        'You pulled the 🫂 2 of Relationships. The number 2 represents change which can be exciting or daunting within relationships. This may result in new experiences and or it may result in lessons learned. No matter what, stick to your values and remember to be kind to yourself.',
        'You pulled the 🔐 2 of Security. The number 2 represents change which can be difficuly if you are trying to build a sense of security in your life. You must accept the fact that you can cultivate security amidst uncertainty. You do not have to prepare for every imagined scenario in order to feel safe.',
        'You pulles the 💞 2 of Spiritual Fulfillment. The number 2 represents change, but in spiritual fulfillment it means you must let go of your need for control in your life. Ground yourself in something you love as you ride the waves of uncertainty.',
        'You pulled the 👺 2 of Self-Sabotage. The number 2 represents change, but within self sabotage, it means you are stagnant and living a life built on fear. There is something you are unsilling to accept or embrace.',
        '🫂 3 of Relationships - Ensure relationships are balanced',
        '🔐 3 of Security - It is okay to ask for help',
        '💞 3 of Spiritual Fulfillment - Healthy routine and boundaries ',
        '👺 3 of Self-Sabotage - Letting others take advantage of your generosity',
        "🫂 4 of Relationships - Tell people how much you love them",
        '🔐 4 of Security - Be grateful for what you have, but do not hold close what is harming you',
        '💞 4 of Spiritual Fulfillment - Remember you are precious, and be as kind to yourself as you are to others',
        '👺 4 of Self-Sabotage - You are holding on to things that are not serving you',
        '🫂 5 of Relationships - It is time to build something new with a person, or demolish a pattern that isn’t healthy. Good communication and open expression is important. Listen to both sides, not just theirs and not just your own.',
        '🔐 5 of Security - It is time to build on your skills and learn from mistakes.',
        '💞 5 of Spiritual Fulfillment - Establish a routine for yourself that allows for spiritual nourishment',
        '👺 5 of Self-Sabotage - You are internalizing too many expectations. You need to reconnect with your internal motivation, and find balance between desire and expectation.',
        '🫂 6 of Relationships - You need to consider where you stand, your boundaries, and the expectations you put on others and yourself. How are they affecting your relationships?',
        '🔐 6 of Security - You are working towards building a sense of security for yourself. Find balance, and remember to consider your values especially with your money, health, and time.',
        '💞 6 of Spiritual Fulfillment - Remember that you cannot pour from an empty cup. Make sure you have a foundation of values and that you are spiritually fulfilled before trying to build the life that you desire. Happiness is an attitude and not a goal.', 
        '👺 6 of Self-Sabotage - You may be building a false sense of security, or basing something on a lie. You may be pretending for others, keeping secrets, or being afraid to acknowledge something. You must address what you are hiding before moving forward. You cannot build a house on sand.',
        '🫂 7 of Relationships - Spend time with people that make you happy.',
        '🔐 7 of Security - Do not spend money recklessly, invest in a budget, and make sure you are using your time wisely. Ensure you have adequate rest time, and do not schedule too many commitments.',
        '💞 7 of Spiritual Fulfillment - Do some shadow work. Meditate, and journal. This is a time to care for yourself spiritually. Cleanse the home, and ensure you feel safe in body and mind.', 
        '👺 7 of Self-Sabotage - You are neglecting yourself for responsibilities, or external obligations. While there are uncomfortable things that need to be done, it is important not to internalize other people’s expectations, and to make space for your own personal fulfillment.',
        '🫂 8 of Relationships - A person or relationship will bring you good fortune if you are open to it.',
        "🔐 8 of Security - Let go of any false sense of security, be grateful for what you have, and maybe you will find happiness in unlikely places. Good fortune awaits, but do not gamble away your luck. Diligence and consistency is important, so that when good fortune and opportunities arrive, you will have room for it. ",
        "💞 8 of Spiritual Fulfillment - You have the ability to move in alignment with your most true nature. Slow down. Do not rush. You are okay. Make space and time to move in alignment with who you are so that you can discern and be receptive to opportunities as they arise. ",
        "👺 8 of Self-Sabotage - You do not allow yourself to accept when good things happen to you. You may have an attitude that you always have the worst luck. Try to slow down, count your blessings, and actively seek good things in your life. You may be surprised how your attitude changes. ",
        "🫂 9 of Relationships - Remember to put out positivity into your relationships. Because the people around you are currently reflecting back to you what you are giving to them. Pay attention. ",
        "🔐 9 of Security - You are living the results of your past actions. Ensure your present actions build a good future for yourself. ",
        "💞 9 of Spiritual Fulfillment - The energy you put out comes back to you. Be careful not to curse someone more than they deserve, or bless someone more than they need. You will be surprised by the consequences. Focus on your own strengths and light and think of how just showing up authentically, and filling your cup can have a positive impact on others. ",
        "👺 9 of Self-Sabotage - You may be wishing on someone's downfall, or perhaps not allowing yourself to elevate. These two are one in the same. Do not point your fingers at others. If you wish harm on others, it may come true for you. Do not become the weed that chokes the flowers in order for it to grow, or you yourself will be plucked. Focus on your own growth, and you will bring blessings and abundance in your life. ",
        "🫂 10 of Relationships - Stop pointing your fingers at others and look within. If you are seeking acknowledgement, appreciation, or recognition, consider why these things may be lacking. If you want someone to see you, you must first look inside yourself. ",
        "🔐 10 of Security - Be honest with how your actions have consequences. Spend your money and time diligently, repay debts, and focus on building a better future for yourself. Sometimes what you don’t know will come back to haunt you. Take inventory of your life, habits, and the actions that go you to where you are, build on what is for your highest good. ",
        "💞 10 of Spiritual Fulfillment - Be kind to yourself. It is time for you to reflect, journal, be honest with yourself, and consider the consequences of your actions. Do not chase people or push anyone away, do not chase security or push away good fortune. It is time to take inventory of how you have been contributing positively and negatively to your own spiritual fulfillment. It is time for silent contemplation. Sit with your thoughts and feelings, journal them or speak them privately to yourself. It is time to be kind yet with discernment of how your patterns may be affecting your life. ",
        "👺 10 of Self-Sabotage - Internalized shame is preventing you from seeing yourself with unclouded visions. You may be defensive or refuse to see your own wrongs. You may struggle with acknowledging the fact that you can make mistakes. Be kind to yourself first, and then take inventory of how your action may be contributing to the consequences.  ",
        "🫂 Jack of Relationships - There is excitement that lies ahead in your relationships. But be careful to take things slow. Not everyone is what they appear to be. Be patient, and do not compromise on your values. ",
        "🔐 Jack of Security - If you are fighting to build of keep something. Consider if it is worth the time, money or sacrifice. If you are embarking on a new endeavor, do it with caution. This card represents vigor, but it is also a warning not to be too naive. Consider all options before acting on a decision. ",
        "💞 Jack of Spiritual Fulfillment - Focus on things that are spiritually fulfilling in your life. Protect your energy. This is not a time to just be allowing anything to influence you. This card usually represents energetic vigor and life, but it can sometimes come with giving more than you receive. Slow down, do not neglect your soul. Know when to fight and when to stay silent.  ",
        "👺 Jack of Self-Sabotage - You are allowing yourself to be run by other people’s commands. You are fighting for others more than you fight for yourself. You are doing other people's bidding by taking on responsibilities they can handle themselves. You may be sacrificing your fulfillment and taking on more responsibilities at work or in life, and spending more time on busywork that is draining to you. You think you are a soldier, but you are a doormat. Remember to speak up for yourself, realign with your values, and find your purpose. Do not be influenced to fight for things that do not align with your truest good. ",  
        "🫂 Queen of Relationships - It is time to trust your intuition. See with your eyes, mind, and heart. If someone has shown you what they are and are not capable of, do not argue with it. Do not try to change another person’s patterns. Manage your expectations and you will have freedom in relationships. Remember, no matter the reason people give you, you cannot let anyone treat you less than you would ever treat them. You cannot allow yourself to put up with things that you will never put out. ",
        "🔐 Queen of Security - Use discernment in where your time and money is being spent. Do an inventory of your capacity, and trust your body's need for rest, and allow yourself to pursue an idea when you feel ready. Use discernment to balance self discipline and self compassion. These are not opposites, they work together in harmony.",
        "💞 Queen of Spiritual Fulfillment - Tune into your intuition. Do not align yourself with things that do not feel right. Why talk yourself out of something you already know in your heart to be true?",
        "👺 Queen of Self-Sabotage - You are cut off from your inner self. You are having trouble connecting with your intuition and how you feel. Take some time to yourself for self reflection.",
        "🫂 King of Relationships - There is an imbalance of power in a relationship. You may need to know when to assert yourself, and know when to compromise. A good king knows how to fight, when to admit defeat, and when to negotiate. Listen and think before you speak. ",
        "🔐 King of Security - It is now time to govern what comes in and out of your life, what you focus on, and how you spend your time. You are the ruler and gatekeeper of your life. It is time to stick to your values, evaluate the standards you have for yourself, and live by your word. Do not over-promise and underdeliver. It is time to take the reins of your life and take action to build a better future for yourself.",
        "💞 King of Spiritual Fulfillment - Take inventory of the tools you have available. You cannot build the life you want with tools you do not understand how to use. Take the time to see what you have to work with spiritually and emotionally, and do not operate in a manner that will drain you faster than you can recharge. Consider what you let affect you spiritually and what you allow into your body and mind.",
        "👺 King of Self-Sabotage - You need to let go of you need for control. Some things you cannot influence, and some people you cannot reach. You are putting in effort to try to get a result from something with too many variables. You need to step back, see things from a birds eye view, and focus only on what you are able. Allow things to dissolve in their natural consequence. Some things are inevitable, and rather than trying to control the outcome, it is best to focus more on learning, growing, preparation, and adaptation.",
        "🫂 Ace of Relationships - Be open about your wants and needs, but be careful what you wish for. You may notice you have the ability to manifest what you desire, but this does not come at the cost of any other person’s autonomy. Sometimes relationship outcomes may not be what you expect, so be clear about what you want and need. If you are, you will be able to move in the directions of your desires.",
        "🔐 Ace of Security - Accept that the life you are now working toward is the life you want. You have the ability to manifest the life you want, but make sure it is what you truly want. Rather than focus on the external, focus on how you want to feel. Build a life that fills you,  and serves you. Make spaces of safety and security. Invest in things that yield high returns. Remember to stay aligned with your values",
        "💞 Ace of Spiritual Fulfillment - You have the ability to manifest what is in your highest spiritual good. Engage in things that make you happy. Hobbies, resting things, fulfilling things. It is when you are aligned with your truest self, when you feel safe and comfortable in your skin, this is when you are able to perform in your highest good and manifest what you desire.",
        "👺 Ace of Self-Sabotage - Your lack of belief in yourself is inhibiting your ability to grow and manifest the things you want in your life. Re-align with who you are and what your values are. Accept that both good and bad things can happen to you. Trust you have the ability to play the cards you are dealt.",
          
            ]; //Deck of main messages
                //Randomly return one message        
        }
        headerMessages(){
        const deck = [
        '🫂 2 of Relationships - New relationship or taking existing one to a new level',
        '🔐 2 of Security - Allowing yourself to accept change',
        '💞 2 of Spiritual Fulfillment - Embracing the unknown',
        '👺 2 of Self-Sabotage - Fear and stagnation',
        '🫂 3 of Relationships - Ensure relationships are balanced',
        '🔐 3 of Security - It is okay to ask for help',
        '💞 3 of Spiritual Fulfillment - Healthy routine and boundaries ',
        '👺 3 of Self-Sabotage - Letting others take advantage of your generosity',
        "🫂 4 of Relationships - Tell people how much you love them",
        '🔐 4 of Security - Be grateful for what you have, but do not hold close what is harming you',
        '💞 4 of Spiritual Fulfillment - Remember you are precious, and be as kind to yourself as you are to others',
        '👺 4 of Self-Sabotage - You are holding on to things that are not serving you',
        '🫂 5 of Relationships - It is time to build something new with a person, or demolish a pattern that isn’t healthy. Good communication and open expression is important. Listen to both sides, not just theirs and not just your own.',
        '🔐 5 of Security - It is time to build on your skills and learn from mistakes.',
        '💞 5 of Spiritual Fulfillment - Establish a routine for yourself that allows for spiritual nourishment',
        '👺 5 of Self-Sabotage - You are internalizing too many expectations. You need to reconnect with your internal motivation, and find balance between desire and expectation.',
        '🫂 6 of Relationships - You need to consider where you stand, your boundaries, and the expectations you put on others and yourself. How are they affecting your relationships?',
        '🔐 6 of Security - You are working towards building a sense of security for yourself. Find balance, and remember to consider your values especially with your money, health, and time.',
        '💞 6 of Spiritual Fulfillment - Remember that you cannot pour from an empty cup. Make sure you have a foundation of values and that you are spiritually fulfilled before trying to build the life that you desire. Happiness is an attitude and not a goal.', 
        '👺 6 of Self-Sabotage - You may be building a false sense of security, or basing something on a lie. You may be pretending for others, keeping secrets, or being afraid to acknowledge something. You must address what you are hiding before moving forward. You cannot build a house on sand.',
        '🫂 7 of Relationships - Spend time with people that make you happy.',
        '🔐 7 of Security - Do not spend money recklessly, invest in a budget, and make sure you are using your time wisely. Ensure you have adequate rest time, and do not schedule too many commitments.',
        '💞 7 of Spiritual Fulfillment - Do some shadow work. Meditate, and journal. This is a time to care for yourself spiritually. Cleanse the home, and ensure you feel safe in body and mind.', 
        '👺 7 of Self-Sabotage - You are neglecting yourself for responsibilities, or external obligations. While there are uncomfortable things that need to be done, it is important not to internalize other people’s expectations, and to make space for your own personal fulfillment.',
        '🫂 8 of Relationships - A person or relationship will bring you good fortune if you are open to it.',
        "🔐 8 of Security - Let go of any false sense of security, be grateful for what you have, and maybe you will find happiness in unlikely places. Good fortune awaits, but do not gamble away your luck. Diligence and consistency is important, so that when good fortune and opportunities arrive, you will have room for it. ",
        "💞 8 of Spiritual Fulfillment - You have the ability to move in alignment with your most true nature. Slow down. Do not rush. You are okay. Make space and time to move in alignment with who you are so that you can discern and be receptive to opportunities as they arise. ",
        "👺 8 of Self-Sabotage - You do not allow yourself to accept when good things happen to you. You may have an attitude that you always have the worst luck. Try to slow down, count your blessings, and actively seek good things in your life. You may be surprised how your attitude changes. ",
        "🫂 9 of Relationships - Remember to put out positivity into your relationships. Because the people around you are currently reflecting back to you what you are giving to them. Pay attention. ",
        "🔐 9 of Security - You are living the results of your past actions. Ensure your present actions build a good future for yourself. ",
        "💞 9 of Spiritual Fulfillment - The energy you put out comes back to you. Be careful not to curse someone more than they deserve, or bless someone more than they need. You will be surprised by the consequences. Focus on your own strengths and light and think of how just showing up authentically, and filling your cup can have a positive impact on others. ",
        "👺 9 of Self-Sabotage - You may be wishing on someone's downfall, or perhaps not allowing yourself to elevate. These two are one in the same. Do not point your fingers at others. If you wish harm on others, it may come true for you. Do not become the weed that chokes the flowers in order for it to grow, or you yourself will be plucked. Focus on your own growth, and you will bring blessings and abundance in your life. ",
        "🫂 10 of Relationships - Stop pointing your fingers at others and look within. If you are seeking acknowledgement, appreciation, or recognition, consider why these things may be lacking. If you want someone to see you, you must first look inside yourself. ",
        "🔐 10 of Security - Be honest with how your actions have consequences. Spend your money and time diligently, repay debts, and focus on building a better future for yourself. Sometimes what you don’t know will come back to haunt you. Take inventory of your life, habits, and the actions that go you to where you are, build on what is for your highest good. ",
        "💞 10 of Spiritual Fulfillment - Be kind to yourself. It is time for you to reflect, journal, be honest with yourself, and consider the consequences of your actions. Do not chase people or push anyone away, do not chase security or push away good fortune. It is time to take inventory of how you have been contributing positively and negatively to your own spiritual fulfillment. It is time for silent contemplation. Sit with your thoughts and feelings, journal them or speak them privately to yourself. It is time to be kind yet with discernment of how your patterns may be affecting your life. ",
        "👺 10 of Self-Sabotage - Internalized shame is preventing you from seeing yourself with unclouded visions. You may be defensive or refuse to see your own wrongs. You may struggle with acknowledging the fact that you can make mistakes. Be kind to yourself first, and then take inventory of how your action may be contributing to the consequences.  ",
        "🫂 Jack of Relationships - There is excitement that lies ahead in your relationships. But be careful to take things slow. Not everyone is what they appear to be. Be patient, and do not compromise on your values. ",
        "🔐 Jack of Security - If you are fighting to build of keep something. Consider if it is worth the time, money or sacrifice. If you are embarking on a new endeavor, do it with caution. This card represents vigor, but it is also a warning not to be too naive. Consider all options before acting on a decision. ",
        "💞 Jack of Spiritual Fulfillment - Focus on things that are spiritually fulfilling in your life. Protect your energy. This is not a time to just be allowing anything to influence you. This card usually represents energetic vigor and life, but it can sometimes come with giving more than you receive. Slow down, do not neglect your soul. Know when to fight and when to stay silent.  ",
        "👺 Jack of Self-Sabotage - You are allowing yourself to be run by other people’s commands. You are fighting for others more than you fight for yourself. You are doing other people's bidding by taking on responsibilities they can handle themselves. You may be sacrificing your fulfillment and taking on more responsibilities at work or in life, and spending more time on busywork that is draining to you. You think you are a soldier, but you are a doormat. Remember to speak up for yourself, realign with your values, and find your purpose. Do not be influenced to fight for things that do not align with your truest good. ",  
        "🫂 Queen of Relationships - It is time to trust your intuition. See with your eyes, mind, and heart. If someone has shown you what they are and are not capable of, do not argue with it. Do not try to change another person’s patterns. Manage your expectations and you will have freedom in relationships. Remember, no matter the reason people give you, you cannot let anyone treat you less than you would ever treat them. You cannot allow yourself to put up with things that you will never put out. ",
        "🔐 Queen of Security - Use discernment in where your time and money is being spent. Do an inventory of your capacity, and trust your body's need for rest, and allow yourself to pursue an idea when you feel ready. Use discernment to balance self discipline and self compassion. These are not opposites, they work together in harmony.",
        "💞 Queen of Spiritual Fulfillment - Tune into your intuition. Do not align yourself with things that do not feel right. Why talk yourself out of something you already know in your heart to be true?",
        "👺 Queen of Self-Sabotage - You are cut off from your inner self. You are having trouble connecting with your intuition and how you feel. Take some time to yourself for self reflection.",
        "🫂 King of Relationships - There is an imbalance of power in a relationship. You may need to know when to assert yourself, and know when to compromise. A good king knows how to fight, when to admit defeat, and when to negotiate. Listen and think before you speak. ",
        "🔐 King of Security - It is now time to govern what comes in and out of your life, what you focus on, and how you spend your time. You are the ruler and gatekeeper of your life. It is time to stick to your values, evaluate the standards you have for yourself, and live by your word. Do not over-promise and underdeliver. It is time to take the reins of your life and take action to build a better future for yourself.",
        "💞 King of Spiritual Fulfillment - Take inventory of the tools you have available. You cannot build the life you want with tools you do not understand how to use. Take the time to see what you have to work with spiritually and emotionally, and do not operate in a manner that will drain you faster than you can recharge. Consider what you let affect you spiritually and what you allow into your body and mind.",
        "👺 King of Self-Sabotage - You need to let go of you need for control. Some things you cannot influence, and some people you cannot reach. You are putting in effort to try to get a result from something with too many variables. You need to step back, see things from a birds eye view, and focus only on what you are able. Allow things to dissolve in their natural consequence. Some things are inevitable, and rather than trying to control the outcome, it is best to focus more on learning, growing, preparation, and adaptation.",
        "🫂 Ace of Relationships - Be open about your wants and needs, but be careful what you wish for. You may notice you have the ability to manifest what you desire, but this does not come at the cost of any other person’s autonomy. Sometimes relationship outcomes may not be what you expect, so be clear about what you want and need. If you are, you will be able to move in the directions of your desires.",
        "🔐 Ace of Security - Accept that the life you are now working toward is the life you want. You have the ability to manifest the life you want, but make sure it is what you truly want. Rather than focus on the external, focus on how you want to feel. Build a life that fills you,  and serves you. Make spaces of safety and security. Invest in things that yield high returns. Remember to stay aligned with your values",
        "💞 Ace of Spiritual Fulfillment - You have the ability to manifest what is in your highest spiritual good. Engage in things that make you happy. Hobbies, resting things, fulfilling things. It is when you are aligned with your truest self, when you feel safe and comfortable in your skin, this is when you are able to perform in your highest good and manifest what you desire.",
        "👺 Ace of Self-Sabotage - Your lack of belief in yourself is inhibiting your ability to grow and manifest the things you want in your life. Re-align with who you are and what your values are. Accept that both good and bad things can happen to you. Trust you have the ability to play the cards you are dealt.",
          
            ]; //Deck of main messages
                //Randomly return one message        
        }
        headerMessages(){
        const deck = [
        '🫂 2 of Relationships - New relationship or taking existing one to a new level',
        '🔐 2 of Security - Allowing yourself to accept change',
        '💞 2 of Spiritual Fulfillment - Embracing the unknown',
        '👺 2 of Self-Sabotage - Fear and stagnation',
        '🫂 3 of Relationships - Ensure relationships are balanced',
        '🔐 3 of Security - It is okay to ask for help',
        '💞 3 of Spiritual Fulfillment - Healthy routine and boundaries ',
        '👺 3 of Self-Sabotage - Letting others take advantage of your generosity',
        "🫂 4 of Relationships - Tell people how much you love them",
        '🔐 4 of Security - Be grateful for what you have, but do not hold close what is harming you',
        '💞 4 of Spiritual Fulfillment - Remember you are precious, and be as kind to yourself as you are to others',
        '👺 4 of Self-Sabotage - You are holding on to things that are not serving you',
        '🫂 5 of Relationships - It is time to build something new with a person, or demolish a pattern that isn’t healthy. Good communication and open expression is important. Listen to both sides, not just theirs and not just your own.',
        '🔐 5 of Security - It is time to build on your skills and learn from mistakes.',
        '💞 5 of Spiritual Fulfillment - Establish a routine for yourself that allows for spiritual nourishment',
        '👺 5 of Self-Sabotage - You are internalizing too many expectations. You need to reconnect with your internal motivation, and find balance between desire and expectation.',
        '🫂 6 of Relationships - You need to consider where you stand, your boundaries, and the expectations you put on others and yourself. How are they affecting your relationships?',
        '🔐 6 of Security - You are working towards building a sense of security for yourself. Find balance, and remember to consider your values especially with your money, health, and time.',
        '💞 6 of Spiritual Fulfillment - Remember that you cannot pour from an empty cup. Make sure you have a foundation of values and that you are spiritually fulfilled before trying to build the life that you desire. Happiness is an attitude and not a goal.', 
        '👺 6 of Self-Sabotage - You may be building a false sense of security, or basing something on a lie. You may be pretending for others, keeping secrets, or being afraid to acknowledge something. You must address what you are hiding before moving forward. You cannot build a house on sand.',
        '🫂 7 of Relationships - Spend time with people that make you happy.',
        '🔐 7 of Security - Do not spend money recklessly, invest in a budget, and make sure you are using your time wisely. Ensure you have adequate rest time, and do not schedule too many commitments.',
        '💞 7 of Spiritual Fulfillment - Do some shadow work. Meditate, and journal. This is a time to care for yourself spiritually. Cleanse the home, and ensure you feel safe in body and mind.', 
        '👺 7 of Self-Sabotage - You are neglecting yourself for responsibilities, or external obligations. While there are uncomfortable things that need to be done, it is important not to internalize other people’s expectations, and to make space for your own personal fulfillment.',
        '🫂 8 of Relationships - A person or relationship will bring you good fortune if you are open to it.',
        "🔐 8 of Security - Let go of any false sense of security, be grateful for what you have, and maybe you will find happiness in unlikely places. Good fortune awaits, but do not gamble away your luck. Diligence and consistency is important, so that when good fortune and opportunities arrive, you will have room for it. ",
        "💞 8 of Spiritual Fulfillment - You have the ability to move in alignment with your most true nature. Slow down. Do not rush. You are okay. Make space and time to move in alignment with who you are so that you can discern and be receptive to opportunities as they arise. ",
        "👺 8 of Self-Sabotage - You do not allow yourself to accept when good things happen to you. You may have an attitude that you always have the worst luck. Try to slow down, count your blessings, and actively seek good things in your life. You may be surprised how your attitude changes. ",
        "🫂 9 of Relationships - Remember to put out positivity into your relationships. Because the people around you are currently reflecting back to you what you are giving to them. Pay attention. ",
        "🔐 9 of Security - You are living the results of your past actions. Ensure your present actions build a good future for yourself. ",
        "💞 9 of Spiritual Fulfillment - The energy you put out comes back to you. Be careful not to curse someone more than they deserve, or bless someone more than they need. You will be surprised by the consequences. Focus on your own strengths and light and think of how just showing up authentically, and filling your cup can have a positive impact on others. ",
        "👺 9 of Self-Sabotage - You may be wishing on someone's downfall, or perhaps not allowing yourself to elevate. These two are one in the same. Do not point your fingers at others. If you wish harm on others, it may come true for you. Do not become the weed that chokes the flowers in order for it to grow, or you yourself will be plucked. Focus on your own growth, and you will bring blessings and abundance in your life. ",
        "🫂 10 of Relationships - Stop pointing your fingers at others and look within. If you are seeking acknowledgement, appreciation, or recognition, consider why these things may be lacking. If you want someone to see you, you must first look inside yourself. ",
        "🔐 10 of Security - Be honest with how your actions have consequences. Spend your money and time diligently, repay debts, and focus on building a better future for yourself. Sometimes what you don’t know will come back to haunt you. Take inventory of your life, habits, and the actions that go you to where you are, build on what is for your highest good. ",
        "💞 10 of Spiritual Fulfillment - Be kind to yourself. It is time for you to reflect, journal, be honest with yourself, and consider the consequences of your actions. Do not chase people or push anyone away, do not chase security or push away good fortune. It is time to take inventory of how you have been contributing positively and negatively to your own spiritual fulfillment. It is time for silent contemplation. Sit with your thoughts and feelings, journal them or speak them privately to yourself. It is time to be kind yet with discernment of how your patterns may be affecting your life. ",
        "👺 10 of Self-Sabotage - Internalized shame is preventing you from seeing yourself with unclouded visions. You may be defensive or refuse to see your own wrongs. You may struggle with acknowledging the fact that you can make mistakes. Be kind to yourself first, and then take inventory of how your action may be contributing to the consequences.  ",
        "🫂 Jack of Relationships - There is excitement that lies ahead in your relationships. But be careful to take things slow. Not everyone is what they appear to be. Be patient, and do not compromise on your values. ",
        "🔐 Jack of Security - If you are fighting to build of keep something. Consider if it is worth the time, money or sacrifice. If you are embarking on a new endeavor, do it with caution. This card represents vigor, but it is also a warning not to be too naive. Consider all options before acting on a decision. ",
        "💞 Jack of Spiritual Fulfillment - Focus on things that are spiritually fulfilling in your life. Protect your energy. This is not a time to just be allowing anything to influence you. This card usually represents energetic vigor and life, but it can sometimes come with giving more than you receive. Slow down, do not neglect your soul. Know when to fight and when to stay silent.  ",
        "👺 Jack of Self-Sabotage - You are allowing yourself to be run by other people’s commands. You are fighting for others more than you fight for yourself. You are doing other people's bidding by taking on responsibilities they can handle themselves. You may be sacrificing your fulfillment and taking on more responsibilities at work or in life, and spending more time on busywork that is draining to you. You think you are a soldier, but you are a doormat. Remember to speak up for yourself, realign with your values, and find your purpose. Do not be influenced to fight for things that do not align with your truest good. ",  
        "🫂 Queen of Relationships - It is time to trust your intuition. See with your eyes, mind, and heart. If someone has shown you what they are and are not capable of, do not argue with it. Do not try to change another person’s patterns. Manage your expectations and you will have freedom in relationships. Remember, no matter the reason people give you, you cannot let anyone treat you less than you would ever treat them. You cannot allow yourself to put up with things that you will never put out. ",
        "🔐 Queen of Security - Use discernment in where your time and money is being spent. Do an inventory of your capacity, and trust your body's need for rest, and allow yourself to pursue an idea when you feel ready. Use discernment to balance self discipline and self compassion. These are not opposites, they work together in harmony.",
        "💞 Queen of Spiritual Fulfillment - Tune into your intuition. Do not align yourself with things that do not feel right. Why talk yourself out of something you already know in your heart to be true?",
        "👺 Queen of Self-Sabotage - You are cut off from your inner self. You are having trouble connecting with your intuition and how you feel. Take some time to yourself for self reflection.",
        "🫂 King of Relationships - There is an imbalance of power in a relationship. You may need to know when to assert yourself, and know when to compromise. A good king knows how to fight, when to admit defeat, and when to negotiate. Listen and think before you speak. ",
        "🔐 King of Security - It is now time to govern what comes in and out of your life, what you focus on, and how you spend your time. You are the ruler and gatekeeper of your life. It is time to stick to your values, evaluate the standards you have for yourself, and live by your word. Do not over-promise and underdeliver. It is time to take the reins of your life and take action to build a better future for yourself.",
        "💞 King of Spiritual Fulfillment - Take inventory of the tools you have available. You cannot build the life you want with tools you do not understand how to use. Take the time to see what you have to work with spiritually and emotionally, and do not operate in a manner that will drain you faster than you can recharge. Consider what you let affect you spiritually and what you allow into your body and mind.",
        "👺 King of Self-Sabotage - You need to let go of you need for control. Some things you cannot influence, and some people you cannot reach. You are putting in effort to try to get a result from something with too many variables. You need to step back, see things from a birds eye view, and focus only on what you are able. Allow things to dissolve in their natural consequence. Some things are inevitable, and rather than trying to control the outcome, it is best to focus more on learning, growing, preparation, and adaptation.",
        "🫂 Ace of Relationships - Be open about your wants and needs, but be careful what you wish for. You may notice you have the ability to manifest what you desire, but this does not come at the cost of any other person’s autonomy. Sometimes relationship outcomes may not be what you expect, so be clear about what you want and need. If you are, you will be able to move in the directions of your desires.",
        "🔐 Ace of Security - Accept that the life you are now working toward is the life you want. You have the ability to manifest the life you want, but make sure it is what you truly want. Rather than focus on the external, focus on how you want to feel. Build a life that fills you,  and serves you. Make spaces of safety and security. Invest in things that yield high returns. Remember to stay aligned with your values",
        "💞 Ace of Spiritual Fulfillment - You have the ability to manifest what is in your highest spiritual good. Engage in things that make you happy. Hobbies, resting things, fulfilling things. It is when you are aligned with your truest self, when you feel safe and comfortable in your skin, this is when you are able to perform in your highest good and manifest what you desire.",
        "👺 Ace of Self-Sabotage - Your lack of belief in yourself is inhibiting your ability to grow and manifest the things you want in your life. Re-align with who you are and what your values are. Accept that both good and bad things can happen to you. Trust you have the ability to play the cards you are dealt.",
          
            ]; //Deck of main messages
                //Randomly return one message        
        }
        headerMessages(){
        const deck = [
        '🫂 2 of Relationships - New relationship or taking existing one to a new level',
        '🔐 2 of Security - Allowing yourself to accept change',
        '💞 2 of Spiritual Fulfillment - Embracing the unknown',
        '👺 2 of Self-Sabotage - Fear and stagnation',
        '🫂 3 of Relationships - Ensure relationships are balanced',
        '🔐 3 of Security - It is okay to ask for help',
        '💞 3 of Spiritual Fulfillment - Healthy routine and boundaries ',
        '👺 3 of Self-Sabotage - Letting others take advantage of your generosity',
        "🫂 4 of Relationships - Tell people how much you love them",
        '🔐 4 of Security - Be grateful for what you have, but do not hold close what is harming you',
        '💞 4 of Spiritual Fulfillment - Remember you are precious, and be as kind to yourself as you are to others',
        '👺 4 of Self-Sabotage - You are holding on to things that are not serving you',
        '🫂 5 of Relationships - It is time to build something new with a person, or demolish a pattern that isn’t healthy. Good communication and open expression is important. Listen to both sides, not just theirs and not just your own.',
        '🔐 5 of Security - It is time to build on your skills and learn from mistakes.',
        '💞 5 of Spiritual Fulfillment - Establish a routine for yourself that allows for spiritual nourishment',
        '👺 5 of Self-Sabotage - You are internalizing too many expectations. You need to reconnect with your internal motivation, and find balance between desire and expectation.',
        '🫂 6 of Relationships - You need to consider where you stand, your boundaries, and the expectations you put on others and yourself. How are they affecting your relationships?',
        '🔐 6 of Security - You are working towards building a sense of security for yourself. Find balance, and remember to consider your values especially with your money, health, and time.',
        '💞 6 of Spiritual Fulfillment - Remember that you cannot pour from an empty cup. Make sure you have a foundation of values and that you are spiritually fulfilled before trying to build the life that you desire. Happiness is an attitude and not a goal.', 
        '👺 6 of Self-Sabotage - You may be building a false sense of security, or basing something on a lie. You may be pretending for others, keeping secrets, or being afraid to acknowledge something. You must address what you are hiding before moving forward. You cannot build a house on sand.',
        '🫂 7 of Relationships - Spend time with people that make you happy.',
        '🔐 7 of Security - Do not spend money recklessly, invest in a budget, and make sure you are using your time wisely. Ensure you have adequate rest time, and do not schedule too many commitments.',
        '💞 7 of Spiritual Fulfillment - Do some shadow work. Meditate, and journal. This is a time to care for yourself spiritually. Cleanse the home, and ensure you feel safe in body and mind.', 
        '👺 7 of Self-Sabotage - You are neglecting yourself for responsibilities, or external obligations. While there are uncomfortable things that need to be done, it is important not to internalize other people’s expectations, and to make space for your own personal fulfillment.',
        '🫂 8 of Relationships - A person or relationship will bring you good fortune if you are open to it.',
        "🔐 8 of Security - Let go of any false sense of security, be grateful for what you have, and maybe you will find happiness in unlikely places. Good fortune awaits, but do not gamble away your luck. Diligence and consistency is important, so that when good fortune and opportunities arrive, you will have room for it. ",
        "💞 8 of Spiritual Fulfillment - You have the ability to move in alignment with your most true nature. Slow down. Do not rush. You are okay. Make space and time to move in alignment with who you are so that you can discern and be receptive to opportunities as they arise. ",
        "👺 8 of Self-Sabotage - You do not allow yourself to accept when good things happen to you. You may have an attitude that you always have the worst luck. Try to slow down, count your blessings, and actively seek good things in your life. You may be surprised how your attitude changes. ",
        "🫂 9 of Relationships - Remember to put out positivity into your relationships. Because the people around you are currently reflecting back to you what you are giving to them. Pay attention. ",
        "🔐 9 of Security - You are living the results of your past actions. Ensure your present actions build a good future for yourself. ",
        "💞 9 of Spiritual Fulfillment - The energy you put out comes back to you. Be careful not to curse someone more than they deserve, or bless someone more than they need. You will be surprised by the consequences. Focus on your own strengths and light and think of how just showing up authentically, and filling your cup can have a positive impact on others. ",
        "👺 9 of Self-Sabotage - You may be wishing on someone's downfall, or perhaps not allowing yourself to elevate. These two are one in the same. Do not point your fingers at others. If you wish harm on others, it may come true for you. Do not become the weed that chokes the flowers in order for it to grow, or you yourself will be plucked. Focus on your own growth, and you will bring blessings and abundance in your life. ",
        "🫂 10 of Relationships - Stop pointing your fingers at others and look within. If you are seeking acknowledgement, appreciation, or recognition, consider why these things may be lacking. If you want someone to see you, you must first look inside yourself. ",
        "🔐 10 of Security - Be honest with how your actions have consequences. Spend your money and time diligently, repay debts, and focus on building a better future for yourself. Sometimes what you don’t know will come back to haunt you. Take inventory of your life, habits, and the actions that go you to where you are, build on what is for your highest good. ",
        "💞 10 of Spiritual Fulfillment - Be kind to yourself. It is time for you to reflect, journal, be honest with yourself, and consider the consequences of your actions. Do not chase people or push anyone away, do not chase security or push away good fortune. It is time to take inventory of how you have been contributing positively and negatively to your own spiritual fulfillment. It is time for silent contemplation. Sit with your thoughts and feelings, journal them or speak them privately to yourself. It is time to be kind yet with discernment of how your patterns may be affecting your life. ",
        "👺 10 of Self-Sabotage - Internalized shame is preventing you from seeing yourself with unclouded visions. You may be defensive or refuse to see your own wrongs. You may struggle with acknowledging the fact that you can make mistakes. Be kind to yourself first, and then take inventory of how your action may be contributing to the consequences.  ",
        "🫂 Jack of Relationships - There is excitement that lies ahead in your relationships. But be careful to take things slow. Not everyone is what they appear to be. Be patient, and do not compromise on your values. ",
        "🔐 Jack of Security - If you are fighting to build of keep something. Consider if it is worth the time, money or sacrifice. If you are embarking on a new endeavor, do it with caution. This card represents vigor, but it is also a warning not to be too naive. Consider all options before acting on a decision. ",
        "💞 Jack of Spiritual Fulfillment - Focus on things that are spiritually fulfilling in your life. Protect your energy. This is not a time to just be allowing anything to influence you. This card usually represents energetic vigor and life, but it can sometimes come with giving more than you receive. Slow down, do not neglect your soul. Know when to fight and when to stay silent.  ",
        "👺 Jack of Self-Sabotage - You are allowing yourself to be run by other people’s commands. You are fighting for others more than you fight for yourself. You are doing other people's bidding by taking on responsibilities they can handle themselves. You may be sacrificing your fulfillment and taking on more responsibilities at work or in life, and spending more time on busywork that is draining to you. You think you are a soldier, but you are a doormat. Remember to speak up for yourself, realign with your values, and find your purpose. Do not be influenced to fight for things that do not align with your truest good. ",  
        "🫂 Queen of Relationships - It is time to trust your intuition. See with your eyes, mind, and heart. If someone has shown you what they are and are not capable of, do not argue with it. Do not try to change another person’s patterns. Manage your expectations and you will have freedom in relationships. Remember, no matter the reason people give you, you cannot let anyone treat you less than you would ever treat them. You cannot allow yourself to put up with things that you will never put out. ",
        "🔐 Queen of Security - Use discernment in where your time and money is being spent. Do an inventory of your capacity, and trust your body's need for rest, and allow yourself to pursue an idea when you feel ready. Use discernment to balance self discipline and self compassion. These are not opposites, they work together in harmony.",
        "💞 Queen of Spiritual Fulfillment - Tune into your intuition. Do not align yourself with things that do not feel right. Why talk yourself out of something you already know in your heart to be true?",
        "👺 Queen of Self-Sabotage - You are cut off from your inner self. You are having trouble connecting with your intuition and how you feel. Take some time to yourself for self reflection.",
        "🫂 King of Relationships - There is an imbalance of power in a relationship. You may need to know when to assert yourself, and know when to compromise. A good king knows how to fight, when to admit defeat, and when to negotiate. Listen and think before you speak. ",
        "🔐 King of Security - It is now time to govern what comes in and out of your life, what you focus on, and how you spend your time. You are the ruler and gatekeeper of your life. It is time to stick to your values, evaluate the standards you have for yourself, and live by your word. Do not over-promise and underdeliver. It is time to take the reins of your life and take action to build a better future for yourself.",
        "💞 King of Spiritual Fulfillment - Take inventory of the tools you have available. You cannot build the life you want with tools you do not understand how to use. Take the time to see what you have to work with spiritually and emotionally, and do not operate in a manner that will drain you faster than you can recharge. Consider what you let affect you spiritually and what you allow into your body and mind.",
        "👺 King of Self-Sabotage - You need to let go of you need for control. Some things you cannot influence, and some people you cannot reach. You are putting in effort to try to get a result from something with too many variables. You need to step back, see things from a birds eye view, and focus only on what you are able. Allow things to dissolve in their natural consequence. Some things are inevitable, and rather than trying to control the outcome, it is best to focus more on learning, growing, preparation, and adaptation.",
        "🫂 Ace of Relationships - Be open about your wants and needs, but be careful what you wish for. You may notice you have the ability to manifest what you desire, but this does not come at the cost of any other person’s autonomy. Sometimes relationship outcomes may not be what you expect, so be clear about what you want and need. If you are, you will be able to move in the directions of your desires.",
        "🔐 Ace of Security - Accept that the life you are now working toward is the life you want. You have the ability to manifest the life you want, but make sure it is what you truly want. Rather than focus on the external, focus on how you want to feel. Build a life that fills you,  and serves you. Make spaces of safety and security. Invest in things that yield high returns. Remember to stay aligned with your values",
        "💞 Ace of Spiritual Fulfillment - You have the ability to manifest what is in your highest spiritual good. Engage in things that make you happy. Hobbies, resting things, fulfilling things. It is when you are aligned with your truest self, when you feel safe and comfortable in your skin, this is when you are able to perform in your highest good and manifest what you desire.",
        "👺 Ace of Self-Sabotage - Your lack of belief in yourself is inhibiting your ability to grow and manifest the things you want in your life. Re-align with who you are and what your values are. Accept that both good and bad things can happen to you. Trust you have the ability to play the cards you are dealt.",
          
            ]; //Deck of main messages
                //Randomly return one message        
        }
        headerMessages(){
        const deck = [
        '🫂 2 of Relationships - New relationship or taking existing one to a new level',
        '🔐 2 of Security - Allowing yourself to accept change',
        '💞 2 of Spiritual Fulfillment - Embracing the unknown',
        '👺 2 of Self-Sabotage - Fear and stagnation',
        '🫂 3 of Relationships - Ensure relationships are balanced',
        '🔐 3 of Security - It is okay to ask for help',
        '💞 3 of Spiritual Fulfillment - Healthy routine and boundaries ',
        '👺 3 of Self-Sabotage - Letting others take advantage of your generosity',
        "🫂 4 of Relationships - Tell people how much you love them",
        '🔐 4 of Security - Be grateful for what you have, but do not hold close what is harming you',
        '💞 4 of Spiritual Fulfillment - Remember you are precious, and be as kind to yourself as you are to others',
        '👺 4 of Self-Sabotage - You are holding on to things that are not serving you',
        '🫂 5 of Relationships - It is time to build something new with a person, or demolish a pattern that isn’t healthy. Good communication and open expression is important. Listen to both sides, not just theirs and not just your own.',
        '🔐 5 of Security - It is time to build on your skills and learn from mistakes.',
        '💞 5 of Spiritual Fulfillment - Establish a routine for yourself that allows for spiritual nourishment',
        '👺 5 of Self-Sabotage - You are internalizing too many expectations. You need to reconnect with your internal motivation, and find balance between desire and expectation.',
        '🫂 6 of Relationships - You need to consider where you stand, your boundaries, and the expectations you put on others and yourself. How are they affecting your relationships?',
        '🔐 6 of Security - You are working towards building a sense of security for yourself. Find balance, and remember to consider your values especially with your money, health, and time.',
        '💞 6 of Spiritual Fulfillment - Remember that you cannot pour from an empty cup. Make sure you have a foundation of values and that you are spiritually fulfilled before trying to build the life that you desire. Happiness is an attitude and not a goal.', 
        '👺 6 of Self-Sabotage - You may be building a false sense of security, or basing something on a lie. You may be pretending for others, keeping secrets, or being afraid to acknowledge something. You must address what you are hiding before moving forward. You cannot build a house on sand.',
        '🫂 7 of Relationships - Spend time with people that make you happy.',
        '🔐 7 of Security - Do not spend money recklessly, invest in a budget, and make sure you are using your time wisely. Ensure you have adequate rest time, and do not schedule too many commitments.',
        '💞 7 of Spiritual Fulfillment - Do some shadow work. Meditate, and journal. This is a time to care for yourself spiritually. Cleanse the home, and ensure you feel safe in body and mind.', 
        '👺 7 of Self-Sabotage - You are neglecting yourself for responsibilities, or external obligations. While there are uncomfortable things that need to be done, it is important not to internalize other people’s expectations, and to make space for your own personal fulfillment.',
        '🫂 8 of Relationships - A person or relationship will bring you good fortune if you are open to it.',
        "🔐 8 of Security - Let go of any false sense of security, be grateful for what you have, and maybe you will find happiness in unlikely places. Good fortune awaits, but do not gamble away your luck. Diligence and consistency is important, so that when good fortune and opportunities arrive, you will have room for it. ",
        "💞 8 of Spiritual Fulfillment - You have the ability to move in alignment with your most true nature. Slow down. Do not rush. You are okay. Make space and time to move in alignment with who you are so that you can discern and be receptive to opportunities as they arise. ",
        "👺 8 of Self-Sabotage - You do not allow yourself to accept when good things happen to you. You may have an attitude that you always have the worst luck. Try to slow down, count your blessings, and actively seek good things in your life. You may be surprised how your attitude changes. ",
        "🫂 9 of Relationships - Remember to put out positivity into your relationships. Because the people around you are currently reflecting back to you what you are giving to them. Pay attention. ",
        "🔐 9 of Security - You are living the results of your past actions. Ensure your present actions build a good future for yourself. ",
        "💞 9 of Spiritual Fulfillment - The energy you put out comes back to you. Be careful not to curse someone more than they deserve, or bless someone more than they need. You will be surprised by the consequences. Focus on your own strengths and light and think of how just showing up authentically, and filling your cup can have a positive impact on others. ",
        "👺 9 of Self-Sabotage - You may be wishing on someone's downfall, or perhaps not allowing yourself to elevate. These two are one in the same. Do not point your fingers at others. If you wish harm on others, it may come true for you. Do not become the weed that chokes the flowers in order for it to grow, or you yourself will be plucked. Focus on your own growth, and you will bring blessings and abundance in your life. ",
        "🫂 10 of Relationships - Stop pointing your fingers at others and look within. If you are seeking acknowledgement, appreciation, or recognition, consider why these things may be lacking. If you want someone to see you, you must first look inside yourself. ",
        "🔐 10 of Security - Be honest with how your actions have consequences. Spend your money and time diligently, repay debts, and focus on building a better future for yourself. Sometimes what you don’t know will come back to haunt you. Take inventory of your life, habits, and the actions that go you to where you are, build on what is for your highest good. ",
        "💞 10 of Spiritual Fulfillment - Be kind to yourself. It is time for you to reflect, journal, be honest with yourself, and consider the consequences of your actions. Do not chase people or push anyone away, do not chase security or push away good fortune. It is time to take inventory of how you have been contributing positively and negatively to your own spiritual fulfillment. It is time for silent contemplation. Sit with your thoughts and feelings, journal them or speak them privately to yourself. It is time to be kind yet with discernment of how your patterns may be affecting your life. ",
        "👺 10 of Self-Sabotage - Internalized shame is preventing you from seeing yourself with unclouded visions. You may be defensive or refuse to see your own wrongs. You may struggle with acknowledging the fact that you can make mistakes. Be kind to yourself first, and then take inventory of how your action may be contributing to the consequences.  ",
        "🫂 Jack of Relationships - There is excitement that lies ahead in your relationships. But be careful to take things slow. Not everyone is what they appear to be. Be patient, and do not compromise on your values. ",
        "🔐 Jack of Security - If you are fighting to build of keep something. Consider if it is worth the time, money or sacrifice. If you are embarking on a new endeavor, do it with caution. This card represents vigor, but it is also a warning not to be too naive. Consider all options before acting on a decision. ",
        "💞 Jack of Spiritual Fulfillment - Focus on things that are spiritually fulfilling in your life. Protect your energy. This is not a time to just be allowing anything to influence you. This card usually represents energetic vigor and life, but it can sometimes come with giving more than you receive. Slow down, do not neglect your soul. Know when to fight and when to stay silent.  ",
        "👺 Jack of Self-Sabotage - You are allowing yourself to be run by other people’s commands. You are fighting for others more than you fight for yourself. You are doing other people's bidding by taking on responsibilities they can handle themselves. You may be sacrificing your fulfillment and taking on more responsibilities at work or in life, and spending more time on busywork that is draining to you. You think you are a soldier, but you are a doormat. Remember to speak up for yourself, realign with your values, and find your purpose. Do not be influenced to fight for things that do not align with your truest good. ",  
        "🫂 Queen of Relationships - It is time to trust your intuition. See with your eyes, mind, and heart. If someone has shown you what they are and are not capable of, do not argue with it. Do not try to change another person’s patterns. Manage your expectations and you will have freedom in relationships. Remember, no matter the reason people give you, you cannot let anyone treat you less than you would ever treat them. You cannot allow yourself to put up with things that you will never put out. ",
        "🔐 Queen of Security - Use discernment in where your time and money is being spent. Do an inventory of your capacity, and trust your body's need for rest, and allow yourself to pursue an idea when you feel ready. Use discernment to balance self discipline and self compassion. These are not opposites, they work together in harmony.",
        "💞 Queen of Spiritual Fulfillment - Tune into your intuition. Do not align yourself with things that do not feel right. Why talk yourself out of something you already know in your heart to be true?",
        "👺 Queen of Self-Sabotage - You are cut off from your inner self. You are having trouble connecting with your intuition and how you feel. Take some time to yourself for self reflection.",
        "🫂 King of Relationships - There is an imbalance of power in a relationship. You may need to know when to assert yourself, and know when to compromise. A good king knows how to fight, when to admit defeat, and when to negotiate. Listen and think before you speak. ",
        "🔐 King of Security - It is now time to govern what comes in and out of your life, what you focus on, and how you spend your time. You are the ruler and gatekeeper of your life. It is time to stick to your values, evaluate the standards you have for yourself, and live by your word. Do not over-promise and underdeliver. It is time to take the reins of your life and take action to build a better future for yourself.",
        "💞 King of Spiritual Fulfillment - Take inventory of the tools you have available. You cannot build the life you want with tools you do not understand how to use. Take the time to see what you have to work with spiritually and emotionally, and do not operate in a manner that will drain you faster than you can recharge. Consider what you let affect you spiritually and what you allow into your body and mind.",
        "👺 King of Self-Sabotage - You need to let go of you need for control. Some things you cannot influence, and some people you cannot reach. You are putting in effort to try to get a result from something with too many variables. You need to step back, see things from a birds eye view, and focus only on what you are able. Allow things to dissolve in their natural consequence. Some things are inevitable, and rather than trying to control the outcome, it is best to focus more on learning, growing, preparation, and adaptation.",
        "🫂 Ace of Relationships - Be open about your wants and needs, but be careful what you wish for. You may notice you have the ability to manifest what you desire, but this does not come at the cost of any other person’s autonomy. Sometimes relationship outcomes may not be what you expect, so be clear about what you want and need. If you are, you will be able to move in the directions of your desires.",
        "🔐 Ace of Security - Accept that the life you are now working toward is the life you want. You have the ability to manifest the life you want, but make sure it is what you truly want. Rather than focus on the external, focus on how you want to feel. Build a life that fills you,  and serves you. Make spaces of safety and security. Invest in things that yield high returns. Remember to stay aligned with your values",
        "💞 Ace of Spiritual Fulfillment - You have the ability to manifest what is in your highest spiritual good. Engage in things that make you happy. Hobbies, resting things, fulfilling things. It is when you are aligned with your truest self, when you feel safe and comfortable in your skin, this is when you are able to perform in your highest good and manifest what you desire.",
        "👺 Ace of Self-Sabotage - Your lack of belief in yourself is inhibiting your ability to grow and manifest the things you want in your life. Re-align with who you are and what your values are. Accept that both good and bad things can happen to you. Trust you have the ability to play the cards you are dealt.",
          
            ]; //Deck of main messages
                //Randomly return one message        
        }
        headerMessages(){
        const deck = [
        '🫂 2 of Relationships - New relationship or taking existing one to a new level',
        '🔐 2 of Security - Allowing yourself to accept change',
        '💞 2 of Spiritual Fulfillment - Embracing the unknown',
        '👺 2 of Self-Sabotage - Fear and stagnation',
        '🫂 3 of Relationships - Ensure relationships are balanced',
        '🔐 3 of Security - It is okay to ask for help',
        '💞 3 of Spiritual Fulfillment - Healthy routine and boundaries ',
        '👺 3 of Self-Sabotage - Letting others take advantage of your generosity',
        "🫂 4 of Relationships - Tell people how much you love them",
        '🔐 4 of Security - Be grateful for what you have, but do not hold close what is harming you',
        '💞 4 of Spiritual Fulfillment - Remember you are precious, and be as kind to yourself as you are to others',
        '👺 4 of Self-Sabotage - You are holding on to things that are not serving you',
        '🫂 5 of Relationships - It is time to build something new with a person, or demolish a pattern that isn’t healthy. Good communication and open expression is important. Listen to both sides, not just theirs and not just your own.',
        '🔐 5 of Security - It is time to build on your skills and learn from mistakes.',
        '💞 5 of Spiritual Fulfillment - Establish a routine for yourself that allows for spiritual nourishment',
        '👺 5 of Self-Sabotage - You are internalizing too many expectations. You need to reconnect with your internal motivation, and find balance between desire and expectation.',
        '🫂 6 of Relationships - You need to consider where you stand, your boundaries, and the expectations you put on others and yourself. How are they affecting your relationships?',
        '🔐 6 of Security - You are working towards building a sense of security for yourself. Find balance, and remember to consider your values especially with your money, health, and time.',
        '💞 6 of Spiritual Fulfillment - Remember that you cannot pour from an empty cup. Make sure you have a foundation of values and that you are spiritually fulfilled before trying to build the life that you desire. Happiness is an attitude and not a goal.', 
        '👺 6 of Self-Sabotage - You may be building a false sense of security, or basing something on a lie. You may be pretending for others, keeping secrets, or being afraid to acknowledge something. You must address what you are hiding before moving forward. You cannot build a house on sand.',
        '🫂 7 of Relationships - Spend time with people that make you happy.',
        '🔐 7 of Security - Do not spend money recklessly, invest in a budget, and make sure you are using your time wisely. Ensure you have adequate rest time, and do not schedule too many commitments.',
        '💞 7 of Spiritual Fulfillment - Do some shadow work. Meditate, and journal. This is a time to care for yourself spiritually. Cleanse the home, and ensure you feel safe in body and mind.', 
        '👺 7 of Self-Sabotage - You are neglecting yourself for responsibilities, or external obligations. While there are uncomfortable things that need to be done, it is important not to internalize other people’s expectations, and to make space for your own personal fulfillment.',
        '🫂 8 of Relationships - A person or relationship will bring you good fortune if you are open to it.',
        "🔐 8 of Security - Let go of any false sense of security, be grateful for what you have, and maybe you will find happiness in unlikely places. Good fortune awaits, but do not gamble away your luck. Diligence and consistency is important, so that when good fortune and opportunities arrive, you will have room for it. ",
        "💞 8 of Spiritual Fulfillment - You have the ability to move in alignment with your most true nature. Slow down. Do not rush. You are okay. Make space and time to move in alignment with who you are so that you can discern and be receptive to opportunities as they arise. ",
        "👺 8 of Self-Sabotage - You do not allow yourself to accept when good things happen to you. You may have an attitude that you always have the worst luck. Try to slow down, count your blessings, and actively seek good things in your life. You may be surprised how your attitude changes. ",
        "🫂 9 of Relationships - Remember to put out positivity into your relationships. Because the people around you are currently reflecting back to you what you are giving to them. Pay attention. ",
        "🔐 9 of Security - You are living the results of your past actions. Ensure your present actions build a good future for yourself. ",
        "💞 9 of Spiritual Fulfillment - The energy you put out comes back to you. Be careful not to curse someone more than they deserve, or bless someone more than they need. You will be surprised by the consequences. Focus on your own strengths and light and think of how just showing up authentically, and filling your cup can have a positive impact on others. ",
        "👺 9 of Self-Sabotage - You may be wishing on someone's downfall, or perhaps not allowing yourself to elevate. These two are one in the same. Do not point your fingers at others. If you wish harm on others, it may come true for you. Do not become the weed that chokes the flowers in order for it to grow, or you yourself will be plucked. Focus on your own growth, and you will bring blessings and abundance in your life. ",
        "🫂 10 of Relationships - Stop pointing your fingers at others and look within. If you are seeking acknowledgement, appreciation, or recognition, consider why these things may be lacking. If you want someone to see you, you must first look inside yourself. ",
        "🔐 10 of Security - Be honest with how your actions have consequences. Spend your money and time diligently, repay debts, and focus on building a better future for yourself. Sometimes what you don’t know will come back to haunt you. Take inventory of your life, habits, and the actions that go you to where you are, build on what is for your highest good. ",
        "💞 10 of Spiritual Fulfillment - Be kind to yourself. It is time for you to reflect, journal, be honest with yourself, and consider the consequences of your actions. Do not chase people or push anyone away, do not chase security or push away good fortune. It is time to take inventory of how you have been contributing positively and negatively to your own spiritual fulfillment. It is time for silent contemplation. Sit with your thoughts and feelings, journal them or speak them privately to yourself. It is time to be kind yet with discernment of how your patterns may be affecting your life. ",
        "👺 10 of Self-Sabotage - Internalized shame is preventing you from seeing yourself with unclouded visions. You may be defensive or refuse to see your own wrongs. You may struggle with acknowledging the fact that you can make mistakes. Be kind to yourself first, and then take inventory of how your action may be contributing to the consequences.  ",
        "🫂 Jack of Relationships - There is excitement that lies ahead in your relationships. But be careful to take things slow. Not everyone is what they appear to be. Be patient, and do not compromise on your values. ",
        "🔐 Jack of Security - If you are fighting to build of keep something. Consider if it is worth the time, money or sacrifice. If you are embarking on a new endeavor, do it with caution. This card represents vigor, but it is also a warning not to be too naive. Consider all options before acting on a decision. ",
        "💞 Jack of Spiritual Fulfillment - Focus on things that are spiritually fulfilling in your life. Protect your energy. This is not a time to just be allowing anything to influence you. This card usually represents energetic vigor and life, but it can sometimes come with giving more than you receive. Slow down, do not neglect your soul. Know when to fight and when to stay silent.  ",
        "👺 Jack of Self-Sabotage - You are allowing yourself to be run by other people’s commands. You are fighting for others more than you fight for yourself. You are doing other people's bidding by taking on responsibilities they can handle themselves. You may be sacrificing your fulfillment and taking on more responsibilities at work or in life, and spending more time on busywork that is draining to you. You think you are a soldier, but you are a doormat. Remember to speak up for yourself, realign with your values, and find your purpose. Do not be influenced to fight for things that do not align with your truest good. ",  
        "🫂 Queen of Relationships - It is time to trust your intuition. See with your eyes, mind, and heart. If someone has shown you what they are and are not capable of, do not argue with it. Do not try to change another person’s patterns. Manage your expectations and you will have freedom in relationships. Remember, no matter the reason people give you, you cannot let anyone treat you less than you would ever treat them. You cannot allow yourself to put up with things that you will never put out. ",
        "🔐 Queen of Security - Use discernment in where your time and money is being spent. Do an inventory of your capacity, and trust your body's need for rest, and allow yourself to pursue an idea when you feel ready. Use discernment to balance self discipline and self compassion. These are not opposites, they work together in harmony.",
        "💞 Queen of Spiritual Fulfillment - Tune into your intuition. Do not align yourself with things that do not feel right. Why talk yourself out of something you already know in your heart to be true?",
        "👺 Queen of Self-Sabotage - You are cut off from your inner self. You are having trouble connecting with your intuition and how you feel. Take some time to yourself for self reflection.",
        "🫂 King of Relationships - There is an imbalance of power in a relationship. You may need to know when to assert yourself, and know when to compromise. A good king knows how to fight, when to admit defeat, and when to negotiate. Listen and think before you speak. ",
        "🔐 King of Security - It is now time to govern what comes in and out of your life, what you focus on, and how you spend your time. You are the ruler and gatekeeper of your life. It is time to stick to your values, evaluate the standards you have for yourself, and live by your word. Do not over-promise and underdeliver. It is time to take the reins of your life and take action to build a better future for yourself.",
        "💞 King of Spiritual Fulfillment - Take inventory of the tools you have available. You cannot build the life you want with tools you do not understand how to use. Take the time to see what you have to work with spiritually and emotionally, and do not operate in a manner that will drain you faster than you can recharge. Consider what you let affect you spiritually and what you allow into your body and mind.",
        "👺 King of Self-Sabotage - You need to let go of you need for control. Some things you cannot influence, and some people you cannot reach. You are putting in effort to try to get a result from something with too many variables. You need to step back, see things from a birds eye view, and focus only on what you are able. Allow things to dissolve in their natural consequence. Some things are inevitable, and rather than trying to control the outcome, it is best to focus more on learning, growing, preparation, and adaptation.",
        "🫂 Ace of Relationships - Be open about your wants and needs, but be careful what you wish for. You may notice you have the ability to manifest what you desire, but this does not come at the cost of any other person’s autonomy. Sometimes relationship outcomes may not be what you expect, so be clear about what you want and need. If you are, you will be able to move in the directions of your desires.",
        "🔐 Ace of Security - Accept that the life you are now working toward is the life you want. You have the ability to manifest the life you want, but make sure it is what you truly want. Rather than focus on the external, focus on how you want to feel. Build a life that fills you,  and serves you. Make spaces of safety and security. Invest in things that yield high returns. Remember to stay aligned with your values",
        "💞 Ace of Spiritual Fulfillment - You have the ability to manifest what is in your highest spiritual good. Engage in things that make you happy. Hobbies, resting things, fulfilling things. It is when you are aligned with your truest self, when you feel safe and comfortable in your skin, this is when you are able to perform in your highest good and manifest what you desire.",
        "👺 Ace of Self-Sabotage - Your lack of belief in yourself is inhibiting your ability to grow and manifest the things you want in your life. Re-align with who you are and what your values are. Accept that both good and bad things can happen to you. Trust you have the ability to play the cards you are dealt.",
          
            ]; //Deck of main messages
                //Randomly return one message        
        }

        
}






//Old Code Below Use for 
//Turning the HTML elements into variables to make them easier to work with 
const genbutton = document.getElementById('genbutton') // ID var format

const cardOne = document.getElementById('cardOne') //ID var format

//Keep this deck to remind you of the card suits
const deck = [
        '🫂 2 of Relationships - New relationship or taking existing one to a new level',
        '🔐 2 of Security - Allowing yourself to accept change',
        '💞 2 of Spiritual Fulfillment - Embracing the unknown',
        '👺 2 of Self-Sabotage - Fear and stagnation',
        '🫂 3 of Relationships - Ensure relationships are balanced',
        '🔐 3 of Security - It is okay to ask for help',
        '💞 3 of Spiritual Fulfillment - Healthy routine and boundaries ',
        '👺 3 of Self-Sabotage - Letting others take advantage of your generosity',
        "🫂 4 of Relationships - Tell people how much you love them",
        '🔐 4 of Security - Be grateful for what you have, but do not hold close what is harming you',
        '💞 4 of Spiritual Fulfillment - Remember you are precious, and be as kind to yourself as you are to others',
        '👺 4 of Self-Sabotage - You are holding on to things that are not serving you',
        '🫂 5 of Relationships - It is time to build something new with a person, or demolish a pattern that isn’t healthy. Good communication and open expression is important. Listen to both sides, not just theirs and not just your own.',
        '🔐 5 of Security - It is time to build on your skills and learn from mistakes.',
        '💞 5 of Spiritual Fulfillment - Establish a routine for yourself that allows for spiritual nourishment',
        '👺 5 of Self-Sabotage - You are internalizing too many expectations. You need to reconnect with your internal motivation, and find balance between desire and expectation.',
        '🫂 6 of Relationships - You need to consider where you stand, your boundaries, and the expectations you put on others and yourself. How are they affecting your relationships?',
        '🔐 6 of Security - You are working towards building a sense of security for yourself. Find balance, and remember to consider your values especially with your money, health, and time.',
        '💞 6 of Spiritual Fulfillment - Remember that you cannot pour from an empty cup. Make sure you have a foundation of values and that you are spiritually fulfilled before trying to build the life that you desire. Happiness is an attitude and not a goal.', 
        '👺 6 of Self-Sabotage - You may be building a false sense of security, or basing something on a lie. You may be pretending for others, keeping secrets, or being afraid to acknowledge something. You must address what you are hiding before moving forward. You cannot build a house on sand.',
        '🫂 7 of Relationships - Spend time with people that make you happy.',
        '🔐 7 of Security - Do not spend money recklessly, invest in a budget, and make sure you are using your time wisely. Ensure you have adequate rest time, and do not schedule too many commitments.',
        '💞 7 of Spiritual Fulfillment - Do some shadow work. Meditate, and journal. This is a time to care for yourself spiritually. Cleanse the home, and ensure you feel safe in body and mind.', 
        '👺 7 of Self-Sabotage - You are neglecting yourself for responsibilities, or external obligations. While there are uncomfortable things that need to be done, it is important not to internalize other people’s expectations, and to make space for your own personal fulfillment.',
        '🫂 8 of Relationships - A person or relationship will bring you good fortune if you are open to it.',
        "🔐 8 of Security - Let go of any false sense of security, be grateful for what you have, and maybe you will find happiness in unlikely places. Good fortune awaits, but do not gamble away your luck. Diligence and consistency is important, so that when good fortune and opportunities arrive, you will have room for it. ",
        "💞 8 of Spiritual Fulfillment - You have the ability to move in alignment with your most true nature. Slow down. Do not rush. You are okay. Make space and time to move in alignment with who you are so that you can discern and be receptive to opportunities as they arise. ",
        "👺 8 of Self-Sabotage - You do not allow yourself to accept when good things happen to you. You may have an attitude that you always have the worst luck. Try to slow down, count your blessings, and actively seek good things in your life. You may be surprised how your attitude changes. ",
        "🫂 9 of Relationships - Remember to put out positivity into your relationships. Because the people around you are currently reflecting back to you what you are giving to them. Pay attention. ",
        "🔐 9 of Security - You are living the results of your past actions. Ensure your present actions build a good future for yourself. ",
        "💞 9 of Spiritual Fulfillment - The energy you put out comes back to you. Be careful not to curse someone more than they deserve, or bless someone more than they need. You will be surprised by the consequences. Focus on your own strengths and light and think of how just showing up authentically, and filling your cup can have a positive impact on others. ",
        "👺 9 of Self-Sabotage - You may be wishing on someone's downfall, or perhaps not allowing yourself to elevate. These two are one in the same. Do not point your fingers at others. If you wish harm on others, it may come true for you. Do not become the weed that chokes the flowers in order for it to grow, or you yourself will be plucked. Focus on your own growth, and you will bring blessings and abundance in your life. ",
        "🫂 10 of Relationships - Stop pointing your fingers at others and look within. If you are seeking acknowledgement, appreciation, or recognition, consider why these things may be lacking. If you want someone to see you, you must first look inside yourself. ",
        "🔐 10 of Security - Be honest with how your actions have consequences. Spend your money and time diligently, repay debts, and focus on building a better future for yourself. Sometimes what you don’t know will come back to haunt you. Take inventory of your life, habits, and the actions that go you to where you are, build on what is for your highest good. ",
        "💞 10 of Spiritual Fulfillment - Be kind to yourself. It is time for you to reflect, journal, be honest with yourself, and consider the consequences of your actions. Do not chase people or push anyone away, do not chase security or push away good fortune. It is time to take inventory of how you have been contributing positively and negatively to your own spiritual fulfillment. It is time for silent contemplation. Sit with your thoughts and feelings, journal them or speak them privately to yourself. It is time to be kind yet with discernment of how your patterns may be affecting your life. ",
        "👺 10 of Self-Sabotage - Internalized shame is preventing you from seeing yourself with unclouded visions. You may be defensive or refuse to see your own wrongs. You may struggle with acknowledging the fact that you can make mistakes. Be kind to yourself first, and then take inventory of how your action may be contributing to the consequences.  ",
        "🫂 Jack of Relationships - There is excitement that lies ahead in your relationships. But be careful to take things slow. Not everyone is what they appear to be. Be patient, and do not compromise on your values. ",
        "🔐 Jack of Security - If you are fighting to build of keep something. Consider if it is worth the time, money or sacrifice. If you are embarking on a new endeavor, do it with caution. This card represents vigor, but it is also a warning not to be too naive. Consider all options before acting on a decision. ",
        "💞 Jack of Spiritual Fulfillment - Focus on things that are spiritually fulfilling in your life. Protect your energy. This is not a time to just be allowing anything to influence you. This card usually represents energetic vigor and life, but it can sometimes come with giving more than you receive. Slow down, do not neglect your soul. Know when to fight and when to stay silent.  ",
        "👺 Jack of Self-Sabotage - You are allowing yourself to be run by other people’s commands. You are fighting for others more than you fight for yourself. You are doing other people's bidding by taking on responsibilities they can handle themselves. You may be sacrificing your fulfillment and taking on more responsibilities at work or in life, and spending more time on busywork that is draining to you. You think you are a soldier, but you are a doormat. Remember to speak up for yourself, realign with your values, and find your purpose. Do not be influenced to fight for things that do not align with your truest good. ",  
        "🫂 Queen of Relationships - It is time to trust your intuition. See with your eyes, mind, and heart. If someone has shown you what they are and are not capable of, do not argue with it. Do not try to change another person’s patterns. Manage your expectations and you will have freedom in relationships. Remember, no matter the reason people give you, you cannot let anyone treat you less than you would ever treat them. You cannot allow yourself to put up with things that you will never put out. ",
        "🔐 Queen of Security - Use discernment in where your time and money is being spent. Do an inventory of your capacity, and trust your body's need for rest, and allow yourself to pursue an idea when you feel ready. Use discernment to balance self discipline and self compassion. These are not opposites, they work together in harmony.",
        "💞 Queen of Spiritual Fulfillment - Tune into your intuition. Do not align yourself with things that do not feel right. Why talk yourself out of something you already know in your heart to be true?",
        "👺 Queen of Self-Sabotage - You are cut off from your inner self. You are having trouble connecting with your intuition and how you feel. Take some time to yourself for self reflection.",
        "🫂 King of Relationships - There is an imbalance of power in a relationship. You may need to know when to assert yourself, and know when to compromise. A good king knows how to fight, when to admit defeat, and when to negotiate. Listen and think before you speak. ",
        "🔐 King of Security - It is now time to govern what comes in and out of your life, what you focus on, and how you spend your time. You are the ruler and gatekeeper of your life. It is time to stick to your values, evaluate the standards you have for yourself, and live by your word. Do not over-promise and underdeliver. It is time to take the reins of your life and take action to build a better future for yourself.",
        "💞 King of Spiritual Fulfillment - Take inventory of the tools you have available. You cannot build the life you want with tools you do not understand how to use. Take the time to see what you have to work with spiritually and emotionally, and do not operate in a manner that will drain you faster than you can recharge. Consider what you let affect you spiritually and what you allow into your body and mind.",
        "👺 King of Self-Sabotage - You need to let go of you need for control. Some things you cannot influence, and some people you cannot reach. You are putting in effort to try to get a result from something with too many variables. You need to step back, see things from a birds eye view, and focus only on what you are able. Allow things to dissolve in their natural consequence. Some things are inevitable, and rather than trying to control the outcome, it is best to focus more on learning, growing, preparation, and adaptation.",
        "🫂 Ace of Relationships - Be open about your wants and needs, but be careful what you wish for. You may notice you have the ability to manifest what you desire, but this does not come at the cost of any other person’s autonomy. Sometimes relationship outcomes may not be what you expect, so be clear about what you want and need. If you are, you will be able to move in the directions of your desires.",
        "🔐 Ace of Security - Accept that the life you are now working toward is the life you want. You have the ability to manifest the life you want, but make sure it is what you truly want. Rather than focus on the external, focus on how you want to feel. Build a life that fills you,  and serves you. Make spaces of safety and security. Invest in things that yield high returns. Remember to stay aligned with your values",
        "💞 Ace of Spiritual Fulfillment - You have the ability to manifest what is in your highest spiritual good. Engage in things that make you happy. Hobbies, resting things, fulfilling things. It is when you are aligned with your truest self, when you feel safe and comfortable in your skin, this is when you are able to perform in your highest good and manifest what you desire.",
        "👺 Ace of Self-Sabotage - Your lack of belief in yourself is inhibiting your ability to grow and manifest the things you want in your life. Re-align with who you are and what your values are. Accept that both good and bad things can happen to you. Trust you have the ability to play the cards you are dealt.",
          
    ]; //Deck of cards

let response = deck[Math.floor(Math.random() * deck.length)]; //ensures we return a random response from the list and 
    //Allows the code to still run smoothly if the size of the list is changed


genbutton.addEventListener("click", genCard) //Button listener format 
rel.addEventListener("click", relCard)
sec.addEventListener("click", secCard)
sels.addEventListener("click", selfCard)
spi.addEventListener("click", spirCard)

function genCard() {
        cardOne.innerText = deck[Math.floor(Math.random() * deck.length)]; // Creates paragraph text to screen
        cardTwo.innerText = deck[Math.floor(Math.random() * deck.length)];
        cardThree.innerText = deck[Math.floor(Math.random() * deck.length)];
        cardFour.innerText = deck[Math.floor(Math.random() * deck.length)];
}

function relCard() {
        cardOne.innerText = deck[Math.floor(Math.random() * deck.length)]; // Creates paragraph text to screen
        cardTwo.innerText = deck[Math.floor(Math.random() * deck.length)];
        cardThree.innerText = deck[Math.floor(Math.random() * deck.length)];
        cardFour.innerText = deck[Math.floor(Math.random() * deck.length)];
}

function secCard() {
        cardOne.innerText = deck[Math.floor(Math.random() * deck.length)]; // Creates paragraph text to screen
        cardTwo.innerText = deck[Math.floor(Math.random() * deck.length)];
        cardThree.innerText = deck[Math.floor(Math.random() * deck.length)];
        cardFour.innerText = deck[Math.floor(Math.random() * deck.length)];
}

function selfCard() {
        cardOne.innerText = deck[Math.floor(Math.random() * deck.length)]; // Creates paragraph text to screen
        cardTwo.innerText = deck[Math.floor(Math.random() * deck.length)];
        cardThree.innerText = deck[Math.floor(Math.random() * deck.length)];
        cardFour.innerText = deck[Math.floor(Math.random() * deck.length)];
}

function spirCard() {
        cardOne.innerText = deck[Math.floor(Math.random() * deck.length)]; // Creates paragraph text to screen
        cardTwo.innerText = deck[Math.floor(Math.random() * deck.length)];
        cardThree.innerText = deck[Math.floor(Math.random() * deck.length)];
        cardFour.innerText = deck[Math.floor(Math.random() * deck.length)];
}




